### PR TITLE
5pm-4: Remove "From MongoDB" from the title of basic search and Add Data Description

### LINKED ISSUE #116: Remove "From MongoDB" from the title of basic search, since users do not need to know where we are getting the data.
# User Story

* As a user
* I don't see "From MongoDB" on the Search Archived Data page
* So that I don't see confusing and irrelevant information

# Discussion

We should remove "From MongoDB" from the title of basic search, since users do not need to know where we are getting the data.   

We can also explain where data on this page comes from.

# Acceptance Criteria

- [x] New header element on page `https://proj-ucsb-courses-search.herokuapp.com/history/basic` is simply `Search Archived Course Data`
- [x] There is a `<p>` element after the header that explains the source of data for this page.  It may say something such as "Data on this page is accurate for past quarters, but may be incomplete or out of data for current and future quarters."

# Implementation Hints

* Changes will be in the file `javascript/src/main/pages/History/Basic.js`

# Testing hints

Change/add tests in `javascript/src/test/pages/History/Basic.test.js`

First change this line of code:
```
 render(<Basic/>);
```

To: 

```
 const { getByText } =  render(<Basic/>);
```

Then you can add a test like this one:

The test you'll need may be similar to this one on the next line:
  
```javascript
    expect(getByText("Text we are looking for")).toBeInTheDocument();
```

### PR DESCRIPTION
**Pull request by at527**
Removed "From MongoDB" from the title of basic search and added description of course data - "Data on this page is accurate for past quarters, but may be incomplete or out of date for current and future quarters. Course information is not immediately updated."

Closes #116

### CODE REVIEW

**Review by pconrad — APPROVED** [review]
LGTM

**Review by codysasaki — APPROVED** [review]
LGTM

**Comment by boax09** [comment]
Reviewed. LGTM.

**Review by zminshall — APPROVED** [review]
LGTM

**Pull request merged**
