### PR TITLE
Change color in table by class availability

### LINKED ISSUE #62: Displays the number of available spots and changes color if unavailable
# NOTE: This issue already has a PR that is "in progress".

The team is being assigned to finish up this issue.   

You can start by either
* directly making changes to the branch for the PR already in progress, OR
* making a new branch and just using the existing PR as a road map to the changes that need to be made.

I suggest consulting with @andrewhlu who has looked at this in some detail already.

# User Story

As a user I can know the classes' capacities and easily distinguish those which are unavailable, such as cancelled or full classes.

# Acceptance Criteria

Fall 2020 Acceptance Criteria
- [x] Classes display maximum number of enrolled and how many are currently enrolled
- [x] Lecture sections are displayed in a darker color while discussion sections alternate lighter shades of blue
- [x] cancelled and closed classes are displayed with a red background
- [x] ~~full classes are displayed with an orange background~~

Winter 2021 Acceptance Criteria
- [ ] Sections that are full **(including over-enrolled)**, closed, or canceled are displayed with a red background
- [ ] Sections that are close to full (< 20% space*) are displayed with a yellow / orange background
- [ ] Sections that are not full are displayed with a light blue background
- [ ] Lectures are displayed with a darker shade of blue, **except for when the lecture has no sections and is full / close to full**, in which it will follow the same color scheme above
- [ ] Search results page has a key / legend that describes what each color means

(Maybe look into doing the following as well)
- [ ] Instead of listing "Enrolled" and "Max" columns separately, combine them into one column, and display capacity in the format `enrolled # / max #` (i.e. 25/30)
- [ ] Make the table / container wider to accommodate the new columns

\* Feel free to change this percentage if you have a reason for it, I just picked a number

# Implementation Todos

This story was originally started by team 5pm-d in Fall 2020, but the code didn't get merged in because of issues with the PR that weren't resolved by the end of the quarter. Upon reviewing the code again, I proposed the above changes, and I'd like to have these changes made before we merge this feature in. 

The original PR is #74, which has since been marked as a draft. You're welcome to continue your work on this PR (just checkout that branch and add your commits on top), start a new branch and manually integrate the proposed changes from the previous PR, or start fresh entirely. 

The below notes were from F20, I haven't updated it for the new W21 acceptance criteria

Front end:

- [x] add columns for number of students enrolled and maximum number of enrolled
- [x] Modify the proper component to display the lecture colors

Back end:

- No changes needed

Testing:

- [x] Front end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by aezhao065**
This PR closes #62. This branch adds two columns that display the number of enrolled students and the maximum number of enrolled students. It also changes the background colors of sections that are full or unavailable.

### CODE REVIEW

**Review by kunalhandaUCSB — DISMISSED** [review]

**Review by JacquelineMai — APPROVED** [review]

**Review by jvoucsb — APPROVED** [review]

**Comment by andrewhlu** [comment]
I pushed some changes to fix the merge conflict, as well as do some code cleanup / linting to pass the eslint check. Let me know if you don't agree with some of the changes I made.

Some things that I'm noticing while playing around with this code that we might want to address in a future PR:
* The colors aren't described anywhere. I added a comment to do so in code, but we may want to add some sort of key / legend in the actual app as well.
* Should the yellow / red colors also apply to lectures (and especially lectures with no sections)?
* Since this PR adds two additional columns to the table, the table is getting somewhat cramped. We may want to expand the main container a bit.

**Review by jvoucsb — APPROVED** [review]
LGTM

**Comment by mara-downing** [comment]
W21 team: Resolve Andrew's comment above and then this PR will be ready to merge.

**Comment by pconrad** [comment]
New team from W21 is continuing this...

**Pull request closed without merging**
