### PR TITLE
sht, jl - fix footer content

### LINKED ISSUE #126: Update footer to have relevant content
# User Story

As a user I can see the correct app description from the footer so I don't have to figure out what the app is about.

# Discussion

Currently, the footer on the app has this appearance:

image

This is left over from the template repo used to create the app.   Instead it should say something like:

> This app is a class project of [CMPSC 156](https://ucsb-cs156.github.io) at [UCSB](https://ucsb.edu).  Check out the source code [on GitHub](https://github.com/ucsb-cs156-w21/proj-ucsb-courses-search)!

Note that the links in the replacement text go to the correct places.

# Acceptance Criteria

- [x] Footer should have a more accurate description about the app
- [x] Footer should link to the correct GitHub repo ( https://github.com/ucsb-cs156-w21/proj-ucsb-courses-search)
- [x] CMPSC 156 should link to https://ucsb-cs156.github.io
- [x] UCSB should link to https://ucsb.edu

# Implementation Todos

Front end:

- [x] Change text and links in footer (in `javascript/src/main/components/Footer/AppFooter.js`) 

# Testing:

See testing hints below

- [x]  A new test is added to cover the UI change
- [x]  All previous tests still pass

# Testing Hints

In file: `javascript/src/test/components/Footer/AppFooter.test.js`

This test will make sure that the indicated words appear and that they link to the correct places

```
 test("Links are correct", async () => {
    const { getByText } = render(<AppFooter />);
    expect(getByText('CMPSC 156').closest('a')).toHaveAttribute('href', 'https://ucsb-cs156.github.io')
    expect(getByText('UCSB').closest('a')).toHaveAttribute('href', 'https://ucsb.edu')
    expect(getByText('GitHub').closest('a')).toHaveAttribute('href', 'https://github.com/ucsb-cs156-w21/proj-ucsb-courses-search')
  });
```

### PR DESCRIPTION
**Pull request by htransteven**
Adds useful content to the footer such as links to the repo, official UCSB courses search, and others.

Closes #126

### CODE REVIEW

**Comment by andrewhlu** [comment]
Before I review this, can you add a short description of your changes to the PR description and have at least one member of your team that didn't work on this PR review the code?

**Comment by amarantini** [comment]
LGTM

**Review by amarantini — APPROVED** [review]
LGTM

**Comment by htransteven** [comment]
@andrewhlu Can you review and merge?

**Review by andrewhlu — APPROVED** [review]
LGTM

**Pull request merged**
