### PR TITLE
5pm 1 - Add bootstrap Accordion wrapper to JSONPrettyCard

### PR DESCRIPTION
**Pull request by htransteven**
This PR adds Bootstrap's Accordion element to wrap the `JSONPretty` and create a hide/show interface for the user. These changes also include a new test file for the `JSONPrettyCard` card and converts `JSONPrettyCard` to a functional component

### CODE REVIEW

**Review by Zixuan01 — COMMENTED** [review]
It works pretty good when I deploy it on heroku and great job. The courseJSON is hidden and after clicking it will show to the users which satisfies to all Acceptance Criteria. One thing I am wondering is that from the detailed description of issue I find that we can click something (either text, or a button, or an icon) to show the courseJSON but now actually I take time to figure out that I can click the courseJSON to display. Moreover, it seems that you did not follow the Implementation Todos which is to add a "story" into the story directory for the JSONPrettyPanel component, and developing the new functionality there. Once it is working in the storybook, then see if it works in the regular app. I am not sure which one Prof.Conrad or other teaching assistants prefer so it might be better to confirm that.

**Comment by htransteven** [comment]
> It works pretty good when I deploy it on heroku and great job. The courseJSON is hidden and after clicking it will show to the users which satisfies to all Acceptance Criteria. One thing I am wondering is that from the detailed description of issue I find that we can click something (either text, or a button, or an icon) to show the courseJSON but now actually I take time to figure out that I can click the courseJSON to display. Moreover, it seems that you did not follow the Implementation Todos which is to add a "story" into the story directory for the JSONPrettyPanel component, and developing the new functionality there. Once it is working in the storybook, then see if it works in the regular app. I am not sure which one Prof.Conrad or other teaching assistants prefer so it might be better to confirm that.

Thanks for reviewing. Yeah I spoke with Andrew and he said it was fine since we had already implemented it outside of storybook. Plus, this Accordion component is from bootstrap so, in my opinion, it doesn't belong in storybook.

**Review by Zixuan01 — DISMISSED** [review]

**Review by Zixuan01 — APPROVED** [review]
LGTM

**Comment by andrewhlu** [comment]
Can you add a description for this PR?

**Comment by htransteven** [comment]
> Can you add a description for this PR?

Done

**Review by pconrad — APPROVED** [review]
I agree that it would have been good to add to the storybook, but that can be a separate issue.

**Pull request merged**
