### PR TITLE
5pm 1 add header

### PR DESCRIPTION
**Pull request by hirish99**
We added a header on the Average Class Size By Department option under the Statistics Tab.

This image shows the change:
Screen Shot 2021-02-23 at 5 42 28 PM

### CODE REVIEW

**Review by AnikaArora — DISMISSED** [review]
Looks good!

**Review by andrewhlu — CHANGES_REQUESTED** [review]
It looks like you have failing tests and some `eslint` errors that need to be resolved. Can you address these and then re-request me for review?

**Review by pconrad — APPROVED** [review]
LGTM

**Review by AnikaArora — APPROVED** [review]
Looks good now!

**Review by andrewhlu — APPROVED** [review]

**Pull request merged**
