### PR TITLE
AL - Add S21 quarter to basic search

### PR DESCRIPTION
**Pull request by andrewhlu**
It's time to register for Spring classes! This short PR adds the S21 option for the Basic Course Search on the main page and sets it as the default option.

This change is only being made in `BasicCourseSearchForm` for now, since the MongoDB archive doesn't have anything for S21 yet. I'll make a separate PR for the dropdowns of the archived course searches, which we can merge in when the MongoDB archive is made.

### CODE REVIEW

**Review by JacquelineMai — APPROVED** [review]
Code changes look good, but does this branch also need the codecov fix to get the checks to pass?

**Comment by andrewhlu** [comment]
> Code changes look good, but does this branch also need the codecov fix to get the checks to pass?

Yea, that's why I'm going to hold off on merging this one until after #134 gets merged in. That's the PR that should supposedly fix Codecov.

**Review by pconrad — APPROVED** [review]
LGTM

**Review by pconrad — COMMENTED** [review]
LGTM... and the Mongo collection is updated for S21 now

**Pull request merged**
