### PR TITLE
5pm 1 - Move the quarter manipulation code and test to src/main/java/edu…

### PR DESCRIPTION
**Pull request by Zixuan01**
In this PR, we address stories for #188 to migrate https://github.com/ucsb-cs56-w20/ucsb-courses-search/blob/master/src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/utilities/Quarter.java to src/main/java/edu/ucsb/courses/models in the new app and https://github.com/ucsb-cs56-w20/ucsb-courses-search/blob/master/src/test/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/utilities/TestQuarter.java to 
src/test/java/edu/ucsb/courses/models and fix up the package name. 
This PR only creates two files for Quarter.java and TestQuarter.java.

### CODE REVIEW

**Comment by andrewhlu** [comment]
It looks like you haven't written any tests for your changes. Please write some unit tests for your changes and then re-request your team and the staff for a review.

If you could also mark this PR as a "draft" while you're doing so, that would be helpful. Thanks!

**Review by pconrad — APPROVED** [review]
LGTM.   Nice job on adding the tests that weren't there in the original.

**Comment by pconrad** [comment]
This one will be 20 points when merged because of the extra complexity in converting tests from JUnit4 to Junit5, and adding extra tests that were not in the original.

**Review by AnikaArora — APPROVED** [review]
Looks good to me as well!

**Pull request merged**
