### PR TITLE
5pm-4: Combine number and suffix fields in Course Name Search

### LINKED ISSUE #159: Combine the course number and course suffix into a single field.
# User Story

As a user, I can enter the course number and possible suffix in one field on the "Search by Course Name" page so that I don't have to click on too many fields.

# Acceptance Criteria
- [x] "Search by Course Name" form no longer has a field for course suffix.
- [x] Course suffix can be entered in course number field
- [x] The search behaves as it did before removing the field in all other ways 

# Implementation Todos

Front end:

- [x] Create single field to enter course name and suffix instead of two.

Back end:

Nothing to do.

Testing:

- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by at527**
This pull request closes #159 "Combine the course number and course suffix into a single field." .

- The Search by Course Name page (history/courseName) no longer has separate fields for course number and course suffix.
- Users can input the number and suffix together in the Course Name box (e.g. "130A").
- The front end Javascript code extracts numbers and letters from the input to set the courseNumber and courseSuf fields.
- Tests for inputs with and without suffix were added, maintaining full coverage.

### CODE REVIEW

**Review by codysasaki — DISMISSED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
I found a bug.

Steps to reproduce:
* Search for CMPSC 130A
* Then search for CMPSC 138
* Desired: you find CMPSC 138
* Observed: CMPSC 138 cannot be found.

I have confirmed that this bug occurs on this branch, but not on the main branch. (i.e. not on https://proj-ucsb-courses-search.herokuapp.com/history/courseName ).

I suspect that it is because the old value of course suffix is not getting cleared out.

It would be good to add a test for this; one where you search for CMPSC 130A, and then search for CMPSC 138, and the second search actually is looking for CMPSC 138, and not CMPSC 138A.    

You may be able to figure out how to do that by looking at existing tests, but if not, ask for help from me or one of the staff.

**Comment by at527** [comment]
The suffix is now explicitly set to an empty string in the case where none is given.

There is a new test that searches for a course number with suffix, then a one without a suffix to check that the field is cleared. It does not pass with the old implementation that did not clear the field.

**Review by codysasaki — APPROVED** [review]
LGTM

**Review by mara-downing — APPROVED** [review]
LGTM

**Pull request merged**
